---
EnableDefaultLinters: true

# Exclude vendor, node_modules, and other non-app code
Exclude:
  - vendor/**/*      # prevents linting gems
  - node_modules/**/* # prevents linting JS deps if present
  - tmp/**/*         # ignores temp build files
  - log/**/*

linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml

  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Style/StringLiterals:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
