# frozen_string_literal: true

alphabetic_seed_stocks = [
  { ticker: "AAPL",
    stock_exchange: "NASDAQ",
    company_name: "Apple Inc.",
    company_website: "https://www.apple.com",
    description: "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.",
    industry: "Consumer Electronics",
    management: "Tim Cook (CEO), Luca Maestri (CFO)",
    employees: 164_000,
    competitor_names: "Samsung, Google, Microsoft, Amazon, Meta",
    sales_growth: 2.8,
    industry_avg_sales_growth: 5.5,
    debt_to_equity: 1.73,
    industry_avg_debt_to_equity: 0.85,
    profit_margin: 23.97,
    industry_avg_profit_margin: 12.50,
    cash_flow: 104_000_000_000.00,
    debt: 123_000_000_000.00,
    price_cents: 23_214 },
  { ticker: "DIS",
    stock_exchange: "NYSE",
    company_name: "The Walt Disney Company",
    company_website: "https://www.thewaltdisneycompany.com",
    description: "The Walt Disney Company operates as an entertainment company worldwide with theme parks, resorts, cruise lines, broadcast television networks, and related products.",
    industry: "Media & Entertainment",
    management: "Bob Iger (CEO), Christine McCarthy (CFO)",
    employees: 220_000,
    competitor_names: "Netflix, Universal, Warner Bros, Paramount",
    sales_growth: 3.2,
    industry_avg_sales_growth: 8.1,
    debt_to_equity: 0.48,
    industry_avg_debt_to_equity: 1.2,
    profit_margin: 6.3,
    industry_avg_profit_margin: 12.3,
    cash_flow: 7_500_000_000.00,
    debt: 46_300_000_000.00,
    price_cents: 11_838 },
  { ticker: "EA",
    stock_exchange: "NASDAQ",
    company_name: "Electronic Arts Inc.",
    company_website: "https://www.ea.com",
    description: "Electronic Arts Inc. develops, markets, publishes, and distributes games, content, and services for game consoles, PCs, mobile phones, and tablets worldwide.",
    industry: "Video Games & Entertainment",
    management: "Andrew Wilson (CEO), Blake Jorgensen (CFO)",
    employees: 13_400,
    competitor_names: "Activision Blizzard, Take-Two Interactive, Ubisoft, Epic Games",
    sales_growth: 2.4,
    industry_avg_sales_growth: 8.9,
    debt_to_equity: 0.12,
    industry_avg_debt_to_equity: 0.25,
    profit_margin: 16.8,
    industry_avg_profit_margin: 13.5,
    cash_flow: 2_100_000_000.00,
    debt: 2_800_000_000.00,
    price_cents: 17_195 },
  { ticker: "F",
    stock_exchange: "NYSE",
    company_name: "Ford Motor Company",
    company_website: "https://www.ford.com",
    description: "Ford Motor Company designs, manufactures, markets, and services a full line of Ford trucks, utility vehicles, and cars worldwide.",
    industry: "Automobiles",
    management: "Jim Farley (CEO), John Lawler (CFO)",
    employees: 190_000,
    competitor_names: "General Motors, Tesla, Toyota, Stellantis",
    sales_growth: 11.8,
    industry_avg_sales_growth: 6.4,
    debt_to_equity: 1.85,
    industry_avg_debt_to_equity: 0.95,
    profit_margin: 3.7,
    industry_avg_profit_margin: 7.2,
    cash_flow: 11_500_000_000.00,
    debt: 96_000_000_000.00,
    price_cents: 1177 },
  { ticker: "GAP",
    stock_exchange: "NYSE",
    company_name: "Gap Inc.",
    company_website: "https://www.gapinc.com",
    description: "Gap Inc. operates as an apparel retail company offering clothing, accessories, and personal care products for men, women, and children under various brand names worldwide.",
    industry: "Specialty Retail",
    management: "Richard Dickson (CEO), Katrina O'Connell (CFO)",
    employees: 95_000,
    competitor_names: "H&M, Zara, Target, American Eagle",
    sales_growth: -1.50,
    industry_avg_sales_growth: 2.80,
    debt_to_equity: 0.28,
    industry_avg_debt_to_equity: 0.45,
    profit_margin: 3.40,
    industry_avg_profit_margin: 5.20,
    cash_flow: 850_000_000.00,
    debt: 1_200_000_000.00,
    price_cents: 2_201 },
  { ticker: "KO",
    stock_exchange: "NYSE",
    company_name: "The Coca-Cola Company",
    company_website: "https://www.coca-colacompany.com",
    description: "The Coca-Cola Company manufactures, retails, and markets nonalcoholic beverage concentrates and syrups worldwide.",
    industry: "Beverages",
    management: "James Quincey (CEO), John Murphy (CFO)",
    employees: 86_200,
    competitor_names: "PepsiCo, Dr Pepper Snapple Group, Monster Beverage",
    sales_growth: 11.2,
    industry_avg_sales_growth: 5.50,
    debt_to_equity: 1.65,
    industry_avg_debt_to_equity: 0.85,
    profit_margin: 25.4,
    industry_avg_profit_margin: 12.50,
    cash_flow: 10_800_000_000.00,
    debt: 37_000_000_000.00,
    price_cents: 6_899 },
  { ticker: "LUV",
    stock_exchange: "NYSE",
    company_name: "Southwest Airlines Co.",
    company_website: "https://www.southwest.com",
    description: "Southwest Airlines Co. operates as a passenger airline company that provides scheduled air transportation services in the United States and near-international markets.",
    industry: "Airlines",
    management: "Bob Jordan (CEO), Tammy Romo (CFO)",
    employees: 66_600,
    competitor_names: "American Airlines, Delta, United, JetBlue",
    sales_growth: 15.2,
    industry_avg_sales_growth: 12.8,
    debt_to_equity: 0.64,
    industry_avg_debt_to_equity: 1.2,
    profit_margin: 8.1,
    industry_avg_profit_margin: 5.4,
    cash_flow: 3_400_000_000.00,
    debt: 13_200_000_000.00,
    price_cents: 3_290 },
  { ticker: "META",
    stock_exchange: "NASDAQ",
    company_name: "Meta Platforms Inc.",
    company_website: "https://about.meta.com",
    description: "Meta Platforms, Inc. develops products that enable people to connect and share with friends and family through mobile devices, personal computers, virtual reality headsets, and wearables worldwide.",
    industry: "Internet & Social Media",
    management: "Mark Zuckerberg (CEO), Susan Li (CFO)",
    employees: 67_317,
    competitor_names: "Google, Apple, TikTok, Twitter, Snapchat",
    sales_growth: 22.7,
    industry_avg_sales_growth: 15.2,
    debt_to_equity: 0.09,
    industry_avg_debt_to_equity: 0.18,
    profit_margin: 29.1,
    industry_avg_profit_margin: 18.7,
    cash_flow: 57_700_000_000.00,
    debt: 9_900_000_000.00,
    price_cents: 73_870 },
  { ticker: "SIRI",
    stock_exchange: "NASDAQ",
    company_name: "Sirius XM Holdings Inc.",
    company_website: "https://www.siriusxm.com",
    description: "Sirius XM Holdings Inc. provides satellite radio services operating in the United States with music, sports, entertainment, comedy, talk, news, traffic, and weather programming.",
    industry: "Broadcasting & Cable TV",
    management: "Jennifer Witz (CEO), Sean Sullivan (CFO)",
    employees: 5_400,
    competitor_names: "Spotify, Pandora, Apple Music, Amazon Music",
    sales_growth: 1.1,
    industry_avg_sales_growth: 4.8,
    debt_to_equity: 2.8,
    industry_avg_debt_to_equity: 1.8,
    profit_margin: 15.2,
    industry_avg_profit_margin: 11.4,
    cash_flow: 2_200_000_000.00,
    debt: 11_000_000_000.00,
    price_cents: 2_374 },
  { ticker: "SONY",
    stock_exchange: "NYSE",
    company_name: "Sony Group Corporation",
    company_website: "https://www.sony.com",
    description: "Sony Group Corporation operates as a technology and media company that develops, produces, manufactures, and sells various products worldwide.",
    industry: "Consumer Electronics",
    management: "Kenichiro Yoshida (CEO), Hiroki Totoki (CFO)",
    employees: 108_900,
    competitor_names: "Samsung, Apple, Nintendo, Microsoft",
    sales_growth: 4.8,
    industry_avg_sales_growth: 6.2,
    debt_to_equity: 0.35,
    industry_avg_debt_to_equity: 0.45,
    profit_margin: 13.2,
    industry_avg_profit_margin: 8.9,
    cash_flow: 8_500_000_000.00,
    debt: 15_200_000_000.00,
    price_cents: 2_752 },
  { ticker: "VZ",
    stock_exchange: "NYSE",
    company_name: "Verizon Communications Inc.",
    company_website: "https://www.verizon.com",
    description: "Verizon Communications Inc., through its subsidiaries, offers communications, technology, information, and entertainment products and services to consumers, businesses, and governmental entities worldwide.",
    industry: "Telecommunications Services",
    management: "Hans Vestberg (CEO), Matt Ellis (CFO)",
    employees: 117_100,
    competitor_names: "AT&T, T-Mobile, Comcast, Charter Communications",
    sales_growth: 2.1,
    industry_avg_sales_growth: 3.8,
    debt_to_equity: 1.8,
    industry_avg_debt_to_equity: 1.5,
    profit_margin: 17.2,
    industry_avg_profit_margin: 12.4,
    cash_flow: 23_700_000_000.00,
    debt: 176_200_000_000.00,
    price_cents: 4_423 }
]

alphabetic_seed_stocks.each do |stock_data|
  stock = Stock.find_or_create_by(ticker: stock_data[:ticker])
  stock.update!(stock_data)
end
