# frozen_string_literal: true

alphabetic_seed_stocks = [
  { ticker: "BAC",  stock_exchange: "NYSE",   company_name: "Bank of America Corporation",    company_website: "https://www.bankofamerica.com", description: "Bank of America Corporation operates as a bank holding company for Bank of America, N.A., which provides various banking and financial products and services.", industry: "Banks", management: "Brian Moynihan (CEO), Alastair Borthwick (CFO)", employees: 216_823, competitor_names: "JPMorgan Chase, Wells Fargo, Citigroup, Goldman Sachs", sales_growth: 2.5, industry_avg_sales_growth: 4.1, debt_to_equity: 1.15, industry_avg_debt_to_equity: 1.25, profit_margin: 32.1, industry_avg_profit_margin: 28.5, cash_flow: 31_200_000_000.00, debt: 294_000_000_000.00, price_cents: 4_512 },
  { ticker: "CCL",  stock_exchange: "NYSE",   company_name: "Carnival Corporation & plc",       company_website: "https://www.carnival.com",     description: "Carnival Corporation & plc operates as a leisure travel company providing cruise vacations and complementary vacation services.", industry: "Travel Services", management: "Josh Weinstein (CEO), David Bernstein (CFO)", employees: 120_000, competitor_names: "Royal Caribbean, Norwegian Cruise Line, MSC Cruises", sales_growth: 15.2, industry_avg_sales_growth: 8.7, debt_to_equity: 3.45, industry_avg_debt_to_equity: 1.85, profit_margin: -2.1, industry_avg_profit_margin: 5.8, cash_flow: 3_800_000_000.00, debt: 28_500_000_000.00, price_cents: 2_185 },
  { ticker: "F",     stock_exchange: "NYSE",   company_name: "Ford Motor Company",         company_website: "https://www.ford.com",         description: "Ford Motor Company designs, manufactures, markets, and services a full line of Ford trucks, utility vehicles, and cars worldwide.",         industry: "Automobiles",         management: "Jim Farley (CEO), John Lawler (CFO)",         employees: 190_000,         competitor_names: "General Motors, Tesla, Toyota, Stellantis",         sales_growth: 11.8,         industry_avg_sales_growth: 6.4,         debt_to_equity: 1.85,         industry_avg_debt_to_equity: 0.95,         profit_margin: 3.7,         industry_avg_profit_margin: 7.2,         cash_flow: 11_500_000_000.00,         debt: 96_000_000_000.00,         price_cents: 1_177 },
  { ticker: "IBIT", stock_exchange: "NASDAQ", company_name: "iShares Bitcoin Trust ETF",         company_website: "https://www.ishares.com",       description: "iShares Bitcoin Trust provides exposure to bitcoin by holding bitcoin and seeks to reflect the performance of bitcoin.", industry: "Exchange Traded Funds", management: "BlackRock Fund Advisors (Sponsor), Samara Cohen (Chief Investment Officer)", employees: 0, competitor_names: "Grayscale Bitcoin Trust, Fidelity Wise Origin Bitcoin Fund, ARK 21Shares Bitcoin ETF", sales_growth: 0.0, industry_avg_sales_growth: 0.0, debt_to_equity: 0.0, industry_avg_debt_to_equity: 0.0, profit_margin: 0.0, industry_avg_profit_margin: 0.0, cash_flow: 0.00, debt: 0.00, price_cents: 4_125 },
  { ticker: "KO",    stock_exchange: "NYSE",   company_name: "The Coca-Cola Company",       company_website: "https://www.coca-colacompany.com", description: "The Coca-Cola Company manufactures, retails, and markets nonalcoholic beverage concentrates and syrups worldwide.", industry: "Beverages", management: "James Quincey (CEO), John Murphy (CFO)", employees: 86_200, competitor_names: "PepsiCo, Dr Pepper Snapple Group, Monster Beverage", sales_growth: 11.2, industry_avg_sales_growth: 5.50, debt_to_equity: 1.65, industry_avg_debt_to_equity: 0.85, profit_margin: 25.4, industry_avg_profit_margin: 12.50, cash_flow: 10_800_000_000.00, debt: 37_000_000_000.00, price_cents: 6_899 },
  { ticker: "KHC",  stock_exchange: "NASDAQ", company_name: "The Kraft Heinz Company",        company_website: "https://www.kraftheinzcompany.com", description: "The Kraft Heinz Company manufactures and markets food and beverage products in the United States and internationally.", industry: "Food Products", management: "Carlos Abrams-Rivera (CEO), Andre Maciel (CFO)", employees: 38_000, competitor_names: "Unilever, Nestle, General Mills, Campbell Soup", sales_growth: -1.2, industry_avg_sales_growth: 3.8, debt_to_equity: 0.87, industry_avg_debt_to_equity: 0.65, profit_margin: 8.9, industry_avg_profit_margin: 11.2, cash_flow: 4_200_000_000.00, debt: 27_800_000_000.00, price_cents: 3_654 },
  { ticker: "NKE",  stock_exchange: "NYSE",   company_name: "Nike, Inc.",                     company_website: "https://www.nike.com",         description: "Nike, Inc. designs, develops, markets, and sells athletic footwear, apparel, equipment, and accessories worldwide.", industry: "Footwear & Accessories", management: "John Donahoe (CEO), Matthew Friend (CFO)", employees: 83_700, competitor_names: "Adidas, Under Armour, Puma, New Balance", sales_growth: 0.3, industry_avg_sales_growth: 4.2, debt_to_equity: 0.68, industry_avg_debt_to_equity: 0.55, profit_margin: 12.9, industry_avg_profit_margin: 9.8, cash_flow: 6_900_000_000.00, debt: 9_600_000_000.00, price_cents: 7_521 },
  { ticker: "MAT",  stock_exchange: "NASDAQ", company_name: "Mattel, Inc.",                   company_website: "https://www.mattel.com",        description: "Mattel, Inc. designs, manufactures, and markets various toy products worldwide under the Mattel, Fisher-Price, American Girl, Thomas & Friends, UNO, and Hot Wheels brands.", industry: "Leisure Products", management: "Ynon Kreiz (CEO), Anthony DiSilvestro (CFO)", employees: 33_000, competitor_names: "Hasbro, LEGO, Spin Master, MGA Entertainment", sales_growth: -1.5, industry_avg_sales_growth: 2.8, debt_to_equity: 2.85, industry_avg_debt_to_equity: 1.25, profit_margin: 17.2, industry_avg_profit_margin: 8.9, cash_flow: 1_100_000_000.00, debt: 2_900_000_000.00, price_cents: 1_892 },
  { ticker: "SONY",  stock_exchange: "NYSE",   company_name: "Sony Group Corporation",      company_website: "https://www.sony.com",  description: "Sony Group Corporation operates as a technology and media company that develops, produces, manufactures, and sells various products worldwide.", industry: "Consumer Electronics", management: "Kenichiro Yoshida (CEO), Hiroki Totoki (CFO)", employees: 108_900, competitor_names: "Samsung, Apple, Nintendo, Microsoft", sales_growth: 4.8, industry_avg_sales_growth: 6.2, debt_to_equity: 0.35, industry_avg_debt_to_equity: 0.45, profit_margin: 13.2, industry_avg_profit_margin: 8.9, cash_flow: 8_500_000_000.00, debt: 15_200_000_000.00, price_cents: 2_752 },
  { ticker: "VZ",    stock_exchange: "NYSE",   company_name: "Verizon Communications Inc.", company_website: "https://www.verizon.com",  description: "Verizon Communications Inc., through its subsidiaries, offers communications, technology, information, and entertainment products and services to consumers, businesses, and governmental entities worldwide.", industry: "Telecommunications Services", management: "Hans Vestberg (CEO), Matt Ellis (CFO)", employees: 117_100, competitor_names: "AT&T, T-Mobile, Comcast, Charter Communications", sales_growth: 2.1, industry_avg_sales_growth: 3.8, debt_to_equity: 1.8, industry_avg_debt_to_equity: 1.5, profit_margin: 17.2, industry_avg_profit_margin: 12.4, cash_flow: 23_700_000_000.00, debt: 176_200_000_000.00, price_cents: 4_423 },
]

alphabetic_seed_stocks.each do |stock_data|
  stock = Stock.find_or_create_by(ticker: stock_data[:ticker])
  stock.update!(stock_data)
end
