# Staging deployment configuration
# Deploy to staging server
servers:
  web:
    hosts:
      - 3.233.183.128

proxy:
  host: 3.233.183.128
  app_port: 3000
  ssl: false

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

# Staging environment variables
env:
  secret:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - DATABASE_URL
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
  clear:
    AWS_BUCKET_NAME: stocks-staging
    AWS_DEFAULT_REGION: us-east-1
    AWS_ENDPOINT_URL: ""
    RAILS_ENV: production
    RAILS_MAX_THREADS: 5
    S3_SKIP_SIGNATURE_VALIDATION: "0"
    WEB_CONCURRENCY: 2

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "stocks_staging_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys_only: true
  keys:
    - ~/.ssh/stocks_staging_web_rsa.pem
