name: RuboCop

on: pull_request

jobs:
  rubocop_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # Caches dependencies

      - name: Run RuboCop
        run: |
          bundle exec rubocop # Run RuboCop checks on the entire codebase
