# frozen_string_literal: true

require "application_system_test_case"

# Clicking save on an invalid form shows the app's own errors, in both places design.md requires: a
# summary at the top and a message at every field, with a rose border that never carries the error alone.
#
# None of it could happen before. Every required input carried `required` and no form set `noValidate`, so
# the browser's native bubble fired first, blocked the submit, and the server never saw it - the one test
# in the suite that needed the summary had to submit a *duplicate* username to get past the browser.
class ValidationErrorsTest < ApplicationSystemTestCase
  def a_classroom_a_teacher_can_edit
    classroom = create(:classroom, :with_trading, grades: [create(:grade, level: 5, name: "5th Grade")])
    teacher = create(:teacher)
    create(:teacher_classroom, teacher:, classroom:)
    sign_in teacher
    classroom
  end

  test "native validation is off, so an invalid submit reaches the server" do
    classroom = a_classroom_a_teacher_can_edit

    visit edit_classroom_path(classroom)

    assert page.evaluate_script("document.querySelector('main form').noValidate"),
           "the form still has native validation, so the browser will block the submit and the app's " \
           "own errors can never render"
  end

  test "saving an invalid form shows the summary and a message at every field" do
    classroom = a_classroom_a_teacher_can_edit

    visit edit_classroom_path(classroom)

    fill_in "Name", with: ""
    uncheck "5th Grade"
    click_on "Update classroom"

    # The summary: one alert, counting, with role=alert so it is announced when it appears.
    within "[data-testid='form-errors']" do
      assert_text "2 errors stopped this classroom being saved"
      assert_text "Name can't be blank"
      assert_text "Grades must have at least one grade"
    end
    assert_selector "#error_explanation[role='alert'][tabindex='-1']"

    # The field: flagged, described, and bordered - the message is generated by the field_error_proc.
    field = page.evaluate_script(<<~JS)
      (function () {
        const el = document.querySelector("#classroom_name");
        const msg = document.getElementById(el.getAttribute("aria-describedby") || "");
        return { invalid: el.getAttribute("aria-invalid"),
                 message: msg ? msg.textContent.trim() : null,
                 border: getComputedStyle(el).borderTopColor,
                 classes: el.className };
      })()
    JS

    assert_equal "true", field["invalid"], "the name field is not marked invalid"
    assert_equal "Name can't be blank", field["message"],
                 "the field has no message of its own, so the error is carried by colour and the " \
                 "summary alone"
    assert_includes field["classes"], "tw-input-error"
    assert_not_includes field["classes"], "tw-input-primary",
                        "both input tokens set a border colour; the winner would be file order"

    # The group: on the fieldset, not on whichever checkbox came first.
    group = page.evaluate_script(<<~JS)
      (function () {
        const fs = document.querySelector("fieldset[aria-invalid='true']");
        if (!fs) return null;
        const msg = document.getElementById(fs.getAttribute("aria-describedby") || "");
        return { legend: fs.querySelector("legend").textContent.trim(),
                 message: msg ? msg.textContent.trim() : null };
      })()
    JS

    assert_not_nil group, "no fieldset was marked invalid"
    assert_includes group["legend"], "Grades"
    assert_equal "Grades must have at least one grade", group["message"]
  end

  # Never colour alone (WCAG 1.4.1): the border and the message both, always.
  test "the rose border never carries the error on its own" do
    classroom = a_classroom_a_teacher_can_edit

    visit edit_classroom_path(classroom)
    fill_in "Name", with: ""
    uncheck "5th Grade"
    click_on "Update classroom"

    unmessaged = page.evaluate_script(<<~JS)
      (function () {
        const out = [];
        document.querySelectorAll("main [aria-invalid='true']").forEach(function (el) {
          const id = el.getAttribute("aria-describedby");
          const msg = id && document.getElementById(id);
          if (!msg || !msg.textContent.trim()) {
            out.push(el.tagName.toLowerCase() + "#" + (el.id || "(no id)"));
          }
        });
        return out;
      })()
    JS

    assert_empty unmessaged, "marked invalid with no message: #{unmessaged.join(', ')}"
  end

  # A valid save is unaffected - the point is that the errors appear when they should, not that the form
  # became harder to submit.
  test "a valid save still saves" do
    classroom = a_classroom_a_teacher_can_edit

    visit edit_classroom_path(classroom)
    fill_in "Name", with: "Renamed By Teacher"
    click_on "Update classroom"

    assert_selector "#notice", text: "Classroom was successfully updated"
    assert_no_selector "[data-testid='form-errors']"
    assert_equal "Renamed By Teacher", classroom.reload.name
  end

  # The student form is hand-written too, and it has a required name.
  test "the student form shows its own errors as well" do
    classroom = create(:classroom, :with_trading)
    student = create(:student, :with_portfolio, classroom:, name: "Ada Lovelace")
    teacher = create(:teacher)
    create(:teacher_classroom, teacher:, classroom:)
    sign_in teacher

    visit edit_classroom_student_path(classroom, student)
    fill_in "Full name", with: ""
    click_on "Update student"

    assert_selector "[data-testid='form-errors']", text: "Name can't be blank"
    assert_selector "#student_name[aria-invalid='true']"
  end

  # Every validation message carries a red icon before it.
  #
  # Reported as the message being "simply grey text": it read as helper text, which is what an uniconed line
  # of slate under a field looks like. The markup even carried `flex items-start gap-1.5` - the fingerprint of
  # an icon the container had been built for and that was never added.
  #
  # It also matters beyond recognition: the input's red border, the icon and the words are three channels, and
  # a reader who cannot see the border has only the last two. An icon is the difference between "this is an
  # error" and "this is advice".
  #
  # red, not rose: rose is this app's destructive-action family (.tw-btn-danger, the confirm dialog), and
  # validation is red - .tw-input-error is border-red-600 and the summary is red-50/200/700. red-600 on white
  # measures 4.77:1, red-700 on the summary's red-50 measures 5.87:1.
  test "every validation message carries a red icon" do
    classroom = a_classroom_a_teacher_can_edit

    visit edit_classroom_path(classroom)

    fill_in "Name", with: ""
    uncheck "5th Grade"
    click_on "Update classroom"

    # `assert_selector` waits; `evaluate_script` does not, so probing straight after the click reads the page
    # as it was before the re-render arrived and reports the summary as missing.
    assert_selector "[data-testid='form-errors']"

    marks = page.evaluate_script(<<~JS)
      (function () {
        const paint = function (colour, over) {
          const c = document.createElement("canvas");
          c.width = c.height = 1;
          const x = c.getContext("2d");
          x.fillStyle = over;
          x.fillRect(0, 0, 1, 1);
          x.fillStyle = colour;
          x.fillRect(0, 0, 1, 1);
          return x.getImageData(0, 0, 1, 1).data;
        };
        const lum = function (v) {
          const f = function (n) { n /= 255; return n <= 0.03928 ? n / 12.92 : Math.pow((n + 0.055) / 1.055, 2.4); };
          return 0.2126 * f(v[0]) + 0.7152 * f(v[1]) + 0.0722 * f(v[2]);
        };
        const ratio = function (a, b) {
          const s = [lum(a), lum(b)].sort(function (m, n) { return n - m; });
          return Math.round(((s[0] + 0.05) / (s[1] + 0.05)) * 100) / 100;
        };
        const groundOf = function (el) {
          let n = el;
          while (n && n !== document.documentElement) {
            const c = getComputedStyle(n).backgroundColor;
            if (c && c !== "rgba(0, 0, 0, 0)") return c;
            n = n.parentElement;
          }
          return "white";
        };
        const read = function (el, name) {
          const svg = el.querySelector("svg");
          if (!svg) return { name: name, icons: 0 };
          const ground = groundOf(svg);
          return { name: name,
                   icons: el.querySelectorAll("svg").length,
                   size: Math.round(svg.getBoundingClientRect().width),
                   contrast: ratio(paint(getComputedStyle(svg).color, ground), paint(ground, "white")) };
        };

        const out = [read(document.querySelector("[data-testid='form-errors']"), "summary")];
        document.querySelectorAll("main form [id$='_error']").forEach(function (msg) {
          out.push(read(msg, msg.id));
        });
        return out;
      })()
    JS

    # The summary, the name field and the grades group.
    assert_operator marks.size, :>=, 3, "expected the summary and two field messages: #{marks.inspect}"

    marks.each do |mark|
      assert_equal 1, mark["icons"], "#{mark['name']} has #{mark['icons']} icons; it reads as helper text"
      # 1.4.11 asks 3:1 for a non-text mark; these clear the 4.5:1 text threshold as well.
      assert_operator mark["contrast"], :>=, 4.5,
                      "#{mark['name']}'s icon is #{mark['contrast']}:1"
    end
  end

  # The field-level message is generated by an initializer, which reaches an app helper through the helpers
  # proxy. `ActionController::Base.helpers` carries Rails' helpers and **none of the app's**, so calling one
  # through it raises NoMethodError at render time - a 500 on every invalid submit rather than a missing icon.
  # It is `ApplicationController.helpers`. Nothing caught that until the server was restarted, because a new
  # initializer is not picked up by code reloading.
  test "an invalid submit renders rather than raising" do
    classroom = a_classroom_a_teacher_can_edit

    visit edit_classroom_path(classroom)
    fill_in "Name", with: ""
    click_on "Update classroom"

    assert_selector "[data-testid='form-errors']"
    assert_no_text "NoMethodError"
    assert_selector "#classroom_name[aria-invalid='true']"
  end
end
